### ISSUE TITLE
Support for spring-webflux 5.3.x

### ISSUE THREAD

**Issue by dave-b-uk** [dtcookie/dynatrace-spring-reactive-weblient-tagging#1]
Since the WebClient class introduce some changes in 5.3.x (like `exchangeToMono`), we'll need an updated version of this tool.

Will 5.3.x be supported?

Thanks

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi @dave-b-uk 

I'm aware of a couple of additional methods that need to get covered when running with later versions. One of our customers extended the solution themselves.
I'm going to look into providing a version that matches 5.3.x early next week.

**Comment by dave-b-uk** [comment]
Thanks a lot @Dynatrace-Reinhard-Pilz for the update, much appreciated

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hello @dave-b-uk,

The main branch now is up to date with the method signatures of 5.3.8. You still have access to the verision for 5.2.8.RELEASE if necessary. For both versions a branch has been introduced.
